import json, os

HERE = os.path.dirname(os.path.abspath(__file__))

with open(os.path.join(HERE, 'levels_solved.json')) as f:
    levels = json.load(f)

lines = []
lines.append('// WORM levels - generated by build_levels.py from levels_src.py (solver-verified).')
lines.append('// Do not edit by hand; edit levels_src.py and rebuild.')
lines.append('const LEVELS = [')
for lv in levels:
    intro = 'null' if not lv['intro'] else json.dumps({
        'kicker': lv['intro'][0], 'title': lv['intro'][1], 'body': lv['intro'][2]})
    grid = json.dumps(lv['grid'])
    lines.append('  {')
    lines.append(f"    name: {json.dumps(lv['name'])},")
    lines.append(f"    world: {json.dumps(lv['world'])},")
    lines.append(f"    theme: {json.dumps(lv['theme'])},")
    lines.append(f"    intro: {intro},")
    lines.append(f"    grid: {grid},")
    lines.append(f"    par: {lv['par']}, budget: {lv['budget']},")
    lines.append(f"    star3: {lv['star3']}, star2: {lv['star2']},")
    if lv.get('patrol'):
        lines.append(f"    patrol: {json.dumps(lv['patrol'])},")
    lines.append('  },')
lines.append('];')
lines.append("if (typeof module !== 'undefined') module.exports = { LEVELS };")

out_path = os.path.join(HERE, 'levels.js')
with open(out_path, 'w') as f:
    f.write('\n'.join(lines) + '\n')
print('wrote', out_path, 'with', len(levels), 'levels')
